services:
  app:
    image: roxsross12/devops-service-flask:1.0.0-app
    build:
      context: ./app
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - VIRTUAL_PORT=8000
      - VIRTUAL_HOST=localhost
    networks:
      - app-network
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
  consumer:
    image: roxsross12/devops-service-flask:1.0.0-consumer
    build:
      context: ./consumer
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    environment:
      - API_URL=http://app:8000
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - CONSUMER_DELAY=1
    depends_on:
      - app
    networks:
      - app-network
    
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy-dev
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge