apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app-flask
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-app-dev
                port:
                  number: 8000
